### PR TITLE
Better gestion of error for recalibration

### PR DESCRIPTION
**Pull request by vincelhx**

### CODE REVIEW

**Review by agrouaze — APPROVED** [review]

**Comment by vincelhx** [comment]
changed rasters chunks

**Review by agrouaze — APPROVED** [review]

**Comment by vincelhx** [comment]
in the last commit I changed RCM calibration : 

we did {varname}_raw = {varname}_raw.where({varname}_raw > 0) . 
But it was a problem in the case of denoising was already applied in DN. It was forcing the future "{varname}_raw" (modified in add_denoised) values to be nan ; 

Now steps are made in the good order : 

-calibration 
-denoising + renaming if necessary ({varname}_raw is with noise while {varname} is without noise 
- then force raw vars to be > 0 

@agrouaze should i do the same logic for S1 & RS2 ?

**Comment by agrouaze** [comment]
> in the last commit I changed RCM calibration :
> 
> we did {varname}_raw = {varname}_raw.where({varname}_raw > 0) . But it was a problem in the case of denoising was already applied in DN. It was forcing the future "{varname}_raw" (modified in add_denoised) values to be nan ;
> 
> Now steps are made in the good order :
> 
> -calibration -denoising + renaming if necessary ({varname}_raw is with noise while {varname} is without noise
> 
>     * then force raw vars to be > 0
> 
> 
> @agrouaze should i do the same logic for S1 & RS2 ?

This as to be discussed with Alexis and Fred, then when the chosen protocol should be described in the doc and I don't see any reason why it would be different from a mission to another. It is also related to 
@alxmouche said "it would be better to keep negative value in the sigma0 (resp. beta0 and gamma0)", also it would be good to keep the 3 variables at the 3 steps in the measurement dataset:

1. digital number
2. sigma0 calibrated
3. sigma0 calibrated+denoised

Then this protocol about the negative values should be described in the `sphinx` documentation.
It also related to https://github.com/umr-lops/xsar/issues/193

**Comment by agrouaze** [comment]
> In the last code I wrote, all the missions perform 'force raw vars to be > 0' at the end of the calibration and denoising process. However, since RCM — with sometimes an already denoised product — is processed differently, the code had to be modified

What is the "last code"? I cannot find any mention of this sentence "force raw vars to be > 0".
The sphinx documentation does not explain the calibration nor the denoising nor this last question "do we let negative values", I think this is important, so if you don't add it, I will do it in another PR.

**Comment by vincelhx** [comment]
#245 will be in marge of making an homogenous code between the three sensors

**Pull request merged**
