### PR TITLE
revisit of rasterization from annotations

### PR DESCRIPTION
**Pull request by agrouaze**
address issue #56 .

- [x] validation
- [x]  add method to get polygons of bursts
- [X] add methods for rasterization in sentinel1_dataset.py and utils.py
- [x] remove obsolet interp methods for lon,lat and inc/elev (after validation)
- [x] test interpolation on a single burst
- [x] test interpolation on several bursts
- [x] limit extent of the `atrack` and `xtrack` coordinates to the image extent
- [x] build doc html
- [x] fix to_lon180 with GRD products

### CODE REVIEW

**Comment by agrouaze** [comment]
last commit allow to get interpolated variables from geoloc annotations in NESZ fashion.
for now it is only in `s1meta` (not added in the `sentinel1_dataset.py`.
The way to test is the following:
```python
atrack = np.arange(10,900)
xtrack = np.arange(40,700)
values_hr = s1ds.s1meta.get_bursts_polygons(atrack,xtrack,s1ds.s1meta.geoloc['incidence'])
valuess = values_hr(atrack,xtrack,s1ds.s1meta.burst_azitime(atrack).astype(float))
```
this first draft implementation is quite slow on the whole subswath. It needs optimization.

**Comment by agrouaze** [comment]
24 March 2022:  @oarcher and @agrouaze decided to 

1. ditch the rasterization of geolocation fields in the "NESZ" fashion
2. compare the content of s1meta.gcps and s1meta.geoloc to be sure that we bring new informations with `geoloc`
3. in a second time remove the methods related to `gcps`

**Comment by agrouaze** [comment]
image

**Comment by agrouaze** [comment]
comparison of s1meta.geoloc versus s1meta.gcps
image
image
geoloc is bringing new fields and keeps informations previsouly provided by gcps.

**Comment by agrouaze** [comment]
commit https://github.com/umr-lops/xsar/pull/57/commits/36dca70c581da3555754656f6533ca00456f11ad
close #19

**Comment by agrouaze** [comment]
latest dataset return : 
image

**Comment by oarcher** [comment]
Merged. Huge contribution to xsar @agrouaze ! :champagne:

**Pull request merged**
