### PR TITLE
Homogene render of start and stop date

### PR DESCRIPTION
**Pull request by yreynaud**
homogeneous output format for dates ( issue : https://github.com/umr-lops/xsar/issues/164 )

### CODE REVIEW

**Review by agrouaze — COMMENTED** [review]
did you tried the modifications on files with the 2 types of date attributes?

**Comment by yreynaud** [comment]
> did you tried the modifications on files with the 2 types of date attributes?

Yes, I tried on both dates from products that have been given by @vincelhx

**Comment by agrouaze** [comment]
> > did you tried the modifications on files with the 2 types of date attributes?
> 
> Yes, I tried on both dates from products that have been given by @vincelhx

Perfect, I let you merge the PR, once Sentinel-1 products are successfully tested.

**Comment by yreynaud** [comment]
> > > did you tried the modifications on files with the 2 types of date attributes?
> > 
> > 
> > Yes, I tried on both dates from products that have been given by @vincelhx
> 
> Perfect, I let you merge the PR, once Sentinel-1 products are successfully tested.

I tried on all s1 product combinations, and on RS2 product. All worked. So, I merge the PR

**Pull request merged**
